[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_KOSIS_API_KEY = "MGJiMDhhOTE1MmFkY2I4MThlNThmOGMxNzMyMjBjZDM="

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
